all:
  children:
    ene_grp_cred_linux:
      children:
        grp_aix:
          hosts:
            host003:
              ansible_ip: 10.1.1.3
              ipaddress: 10.1.1.3
              ostype: aix
        grp_linux:
          hosts:
            host001:
              ansible_ip: 10.1.1.1
              ipaddress: 10.1.1.1
              ostype: linux
            host002:
              ansible_ip: 10.1.1.2
              ipaddress: 10.1.1.2
              ostype: linux
